CREATE TABLE PRICES (
    BRAND_ID    INTEGER     NOT NULL,
    START_DATE  TIMESTAMP,
    END_DATE    TIMESTAMP,
    PRICE_LIST  INTEGER,
    PRODUCT_ID  INTEGER,
    PRIORITY    INTEGER,
    PRICE       DECIMAL(15,2),
    CURRENCY        VARCHAR(3),
    PRIMARY KEY (BRAND_ID, PRICE_LIST, PRODUCT_ID)
);
